<?php

/**
 * This is the model base class for the table "{{term_relationships}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TermRelationships".
 *
 * Columns in table "{{term_relationships}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $object_id
 * @property string $term_taxonomy_id
 * @property integer $term_order
 *
 */
abstract class BaseTermRelationships extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{term_relationships}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TermRelationships|TermRelationships', $n);
	}

	public static function representingColumn() {
		return array(
			'object_id',
			'term_taxonomy_id',
		);
	}

	public function rules() {
		return array(
			array('term_order', 'numerical', 'integerOnly'=>true),
			array('object_id, term_taxonomy_id', 'length', 'max'=>20),
			array('object_id, term_taxonomy_id, term_order', 'default', 'setOnEmpty' => true, 'value' => null),
			array('object_id, term_taxonomy_id, term_order', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'object_id' => Yii::t('app', 'Object'),
			'term_taxonomy_id' => Yii::t('app', 'Term Taxonomy'),
			'term_order' => Yii::t('app', 'Term Order'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('object_id', $this->object_id, true);
		$criteria->compare('term_taxonomy_id', $this->term_taxonomy_id, true);
		$criteria->compare('term_order', $this->term_order);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}