<?php

/**
 * This is the model base class for the table "{{terms}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Terms".
 *
 * Columns in table "{{terms}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $term_id
 * @property string $name
 * @property string $slug
 * @property string $term_group
 *
 */
abstract class BaseTerms extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{terms}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Terms|Terms', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, slug', 'length', 'max'=>200),
			array('term_group', 'length', 'max'=>10),
			array('name, slug, term_group', 'default', 'setOnEmpty' => true, 'value' => null),
			array('term_id, name, slug, term_group', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'term_id' => Yii::t('app', 'Term'),
			'name' => Yii::t('app', 'Name'),
			'slug' => Yii::t('app', 'Slug'),
			'term_group' => Yii::t('app', 'Term Group'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('term_id', $this->term_id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('slug', $this->slug, true);
		$criteria->compare('term_group', $this->term_group, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}