<?php

/**
 * This is the model base class for the table "{{postmeta}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Postmeta".
 *
 * Columns in table "{{postmeta}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $meta_id
 * @property string $post_id
 * @property string $meta_key
 * @property string $meta_value
 *
 */
abstract class BasePostmeta extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{postmeta}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Postmeta|Postmetas', $n);
	}

	public static function representingColumn() {
		return 'meta_key';
	}

	public function rules() {
		return array(
			array('post_id', 'length', 'max'=>20),
			array('meta_key', 'length', 'max'=>255),
			array('meta_value', 'safe'),
			array('post_id, meta_key, meta_value', 'default', 'setOnEmpty' => true, 'value' => null),
			array('meta_id, post_id, meta_key, meta_value', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'meta_id' => Yii::t('app', 'Meta'),
			'post_id' => Yii::t('app', 'Post'),
			'meta_key' => Yii::t('app', 'Meta Key'),
			'meta_value' => Yii::t('app', 'Meta Value'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('meta_id', $this->meta_id, true);
		$criteria->compare('post_id', $this->post_id, true);
		$criteria->compare('meta_key', $this->meta_key, true);
		$criteria->compare('meta_value', $this->meta_value, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}